version: "3.2"

services:
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-net
  member:
    container_name: member
    build:
      context: .
      dockerfile: ./build/Dockerfile
    restart: on-failure
    volumes:
      - ./bin:/home/app/bin
      - ./tests:/home/app/tests
      - ./seeds:/home/app/seeds
      - ./src:/home/app/src
      - ./statics:/home/app/statics
      - ./manage.py:/home/app/manage.py
      - ./setup.py:/home/app/setup.py
    env_file:
      - env/.env.member
      - ${HUNCHO_DIR}/secrets/s3/credentials.txt
    healthcheck:
      test: curl --fail -s member:5000/ping || exit 1
      interval: 60s
      timeout: 5s
      retries: 5
    ports:
      - 20009:5000
    depends_on:
      - member_db
    networks:
      - app-net
  member_db:
    container_name: member_db
    image: postgres:9.6
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - env/.env.member_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U member" ]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - app-net
volumes:
  db_data:
networks:
  app-net:
    driver: bridge