version: "3.2"

services:
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-net
  contestant:
    container_name: contestant
    build:
      context: .
      dockerfile: ./build/Dockerfile
    restart: on-failure
    volumes:
      - ./migrations:/home/app/migrations
      - ./bin:/home/app/bin
      - ./tests:/home/app/tests
      - ./seeds:/home/app/seeds
      - ./src:/home/app/src
      - ./statics:/home/app/statics
      - ./manage.py:/home/app/manage.py
      - ./setup.py:/home/app/setup.py
    env_file:
      - ${HUNCHO_DIR}/env/dev/.env.contestant
      - ${HUNCHO_DIR}/secrets/s3/credentials.txt
    healthcheck:
      test: curl --fail -s contestant:5000/ping || exit 1
      interval: 60s
      timeout: 5s
      retries: 5
    ports:
      - 20009:5000
    depends_on:
      - contestant_db
    networks:
      - app-net
  contestant_db:
    container_name: contestant_db
    image: postgres:9.6
    volumes:
      - ${HUNCHO_DIR}/data/dev/contestant_db/data:/var/lib/postgresql/data/
    env_file:
      - ${HUNCHO_DIR}/env/dev/.env.contestant_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U contestant" ]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - app-net
networks:
  app-net:
    driver: bridge